//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityBuyCandidates.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_BourseEntities : DbContext
    {
        public DB_BourseEntities()
            : base("name=DB_BourseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblBaseInfo> tblBaseInfo { get; set; }
        public DbSet<tblDetailInfo> tblDetailInfo { get; set; }
        public DbSet<tblSecurity> tblSecurity { get; set; }
        public DbSet<tblSecurityGroup> tblSecurityGroup { get; set; }
        public DbSet<tblSecurityHistory> tblSecurityHistory { get; set; }
        public DbSet<tblSecurityHistoryAgah> tblSecurityHistoryAgah { get; set; }
        public DbSet<vwSecurity> vwSecurity { get; set; }
        public DbSet<vwSecurityHistory> vwSecurityHistory { get; set; }
    }
}
