//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityBuyCandidates.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBaseInfo
    {
        public tblBaseInfo()
        {
            this.tblDetailInfo = new HashSet<tblDetailInfo>();
        }
    
        public int BaseInfoID { get; set; }
        public string BaseInfoTitle { get; set; }
        public string BaseInfoTitleLatin { get; set; }
    
        public virtual ICollection<tblDetailInfo> tblDetailInfo { get; set; }
    }
}
