//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityBuyCandidates.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDetailInfo
    {
        public tblDetailInfo()
        {
            this.tblSecurity = new HashSet<tblSecurity>();
            this.tblSecurity1 = new HashSet<tblSecurity>();
            this.tblSecurityHistoryAgah = new HashSet<tblSecurityHistoryAgah>();
            this.tblSecurityHistory = new HashSet<tblSecurityHistory>();
        }
    
        public int DetailInfoID { get; set; }
        public int BaseInfoID { get; set; }
        public string DetailInfoTitle { get; set; }
    
        public virtual tblBaseInfo tblBaseInfo { get; set; }
        public virtual ICollection<tblSecurity> tblSecurity { get; set; }
        public virtual ICollection<tblSecurity> tblSecurity1 { get; set; }
        public virtual ICollection<tblSecurityHistoryAgah> tblSecurityHistoryAgah { get; set; }
        public virtual ICollection<tblSecurityHistory> tblSecurityHistory { get; set; }
    }
}
