//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityBuyCandidates.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSecurityHistory
    {
        public int SecurityHistoryID { get; set; }
        public int SecurityID { get; set; }
        public System.DateTime Date { get; set; }
        public string DatePersian { get; set; }
        public int ClosingPrice { get; set; }
        public int OpeningPrice { get; set; }
        public int HighestPrice { get; set; }
        public int LowestPrice { get; set; }
        public long Volume { get; set; }
        public int AdjustmentTypeID { get; set; }
        public Nullable<int> NaturalBuyCount { get; set; }
        public Nullable<int> LegalBuyCount { get; set; }
        public Nullable<int> NaturalSellCount { get; set; }
        public Nullable<int> LegalSellCount { get; set; }
        public Nullable<long> NaturalBuyVolume { get; set; }
        public Nullable<long> LegalBuyVolume { get; set; }
        public Nullable<long> NaturalSellVolume { get; set; }
        public Nullable<long> LegalSellVolume { get; set; }
    
        public virtual tblDetailInfo tblDetailInfo { get; set; }
        public virtual tblSecurity tblSecurity { get; set; }
    }
}
